development:
  adapter: postgresql
  encoding: unicode
  database: shifter_development
  pool: 5
  username: shifter
  password: shifter

test:
  adapter: postgresql
  encoding: unicode
  database: shifter_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'shifter' %>
  password: <%= ENV['TRAVIS'] ? '' : 'shifter' %>

production:
  adapter: postgresql
  encoding: unicode
  database: shifter_production
  pool: 5
  username: shifter
  password: shifter
